### ISSUE TITLE
TypeError: Object of type Decimal is not JSON serializable

### ISSUE THREAD

**Issue by kristapsk** [nickfarrow/SatSale#26]
Upon receiving incoming Bitcoin onchain transaction, log output for me is full with the following, each second, regardless of actual confirmation count:
```
Invoice ffddefcb213d42c4a550b4a528ffa47e status: {'payment_complete': 0, 'confirmed_paid': 0, 'unconfirmed_paid': Decimal('0E-8'), 'time_left': 1269.8989429473877}
[2021-12-15 12:22:36,511] ERROR in app: Exception on /api/checkpayment [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 329, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/user/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 350, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/flask_restplus/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Decimal is not JSON serializable
```
Tested with recent development build of Bitcoin Core on signet.
```
~/git/SatSale $ git log | head -n 1
commit 7eba6cf172e7ada59c9bf0f7210cbdbfd3828127
```

**Comment by nickfarrow** [comment]
Thanks for the report
Fixed in https://github.com/nickfarrow/SatSale/commit/ed29beededd0d1952865ce59b6a6d2b736993cca

**Comment by kristapsk** [comment]
Post-merge tACK, this solves issue for me.

**Comment by kristapsk** [comment]
Hmm, but for some reason confirmations are still not being detected (not sure it's related to this issue, will try looking at source later, unless you have idea what's happening there).
```
$ bitcoin-cli -signet -rpcwallet=signet getreceivedbylabel 42413f3ec6c0435b970c0b227d548462 2
0.00082153
```
SatSale still outputs:
```
Invoice 42413f3ec6c0435b970c0b227d548462 status: {'payment_complete': 0, 'confirmed_paid': 0.0, 'unconfirmed_paid': 0.0, 'time_left': 891.8794193267822}
Invoice 42413f3ec6c0435b970c0b227d548462 status: {'payment_complete': 0, 'confirmed_paid': 0.0, 'unconfirmed_paid': 0.0, 'time_left': 890.8757379055023}
Invoice 42413f3ec6c0435b970c0b227d548462 status: {'payment_complete': 0, 'confirmed_paid': 0.0, 'unconfirmed_paid': 0.0, 'time_left': 889.8755114078522}
Invoice 42413f3ec6c0435b970c0b227d548462 status: {'payment_complete': 0, 'confirmed_paid': 0.0, 'unconfirmed_paid': 0.0, 'time_left': 888.8762505054474}
```

**Comment by nickfarrow** [comment]
@kristapsk SatSale is a bit misleading here, the `Invoice` is actually a UUID not an address/ln-invoice. Previously I silenced the address from being printed on `/checkpayment` as it got a bit spammy. `Invoice` should probably be relabled `uuid` or `invoice-uuid`, or bring back address printing altogether. Which do you think?

Does signet not have any address checking? 😅

**Comment by kristapsk** [comment]
@nickfarrow Yes, I know it's not address, looked at code. It's added as a label when generating address. That's why I used `getreceivedbylabel` not `getreceivedbyaddress` in example.

**Comment by nickfarrow** [comment]
@kristapsk my bad, thought you were calling `getreceivedbyaddress`. 

This is pretty bad! I haven't been able to replicate yet.
I wonder if it has something to do with which wallet RPC calls are being made to? Like in https://github.com/nickfarrow/SatSale/issues/27

I wonder what a `print(transactions)` here would output
https://github.com/nickfarrow/SatSale/blob/master/node/bitcoind.py#L89

**Comment by kristapsk** [comment]
@nickfarrow It looks to me it's because I sent tx from the same wallet configured for SatSale (listed as "Payment to yourself" in bitcoin-qt). Your approach gets both incoming and outgoing as different transactions (although they are the same tx on a blockchain) and the order is possibly random, so then with some probablity amount will be negative. Better approach is to add UUID (label) as argument to `listtransactions` RPC, it has two benefits: 1) only incoming transactions will be returned, 2) less data to process in Python code. Your code already do it that way for c-lightning. I will look into implementing this and send a PR.

Couldn't test this properly so far because signet blocks were slow and different problem appeared before tx confirmed:
```
[2021-12-20 22:48:26,314] ERROR in app: Exception on /api/checkpayment [GET]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.local/lib/python3.8/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/user/git/SatSale/satsale.py", line 172, in get
    status = check_payment_status(uuid)
  File "/home/user/git/SatSale/satsale.py", line 260, in check_payment_status
    conf_paid, unconf_paid = node.check_payment(invoice["address"])
  File "/home/user/git/SatSale/node/bitcoind.py", line 87, in check_payment
    transactions = self.rpc.listtransactions()
  File "/home/user/.local/lib/python3.8/site-packages/bitcoinrpc/authproxy.py", line 133, in __call__
    self.__conn.request('POST', self.__url.path, postdata,
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1046, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 968, in send
    self.sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```
It did polling successfully before for about 18 minutes.
